image = "${SCRATCH}/ce-images/vllm-cpu.sqsh"

mounts = [
    "/capstor",
    "/iopsstor"
] 

workdir = "${SCRATCH}/" 

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true" 
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
NCCL_DEBUG = "WARN" 
CUDA_CACHE_DISABLE = "1" 
TORCH_NCCL_ASYNC_ERROR_HANDLING = "1" 
MPICH_GPU_SUPPORT_ENABLED = "0"
CUDA_VISIBLE_DEVICES= "0,1,2,3"
LOG_LEVEL = "WARN"